### PR TITLE
fix(1001): add margin on av side menu collapse button

### LINKED ISSUE #1001: AvSideMenu ajouter un padding
l'icon pour fermer l`AvSideMenu` devrait avoir un padding, actuellement le bouton pour fermer le menu est collé à la ligne verticale, ce qui n'est pas très esthétique

Image

### PR DESCRIPTION
**Pull request by Nathan-Pignon**
🚨 **Reminder:** This template is not meant to be submitted as part of the pull request body.  
Please use it as a guide, and replace or remove it before creating your PR.

Thanks again for your work! 💪

# Read Before Submissions

Thank you for your contributions to CoFolio.

When you publish the pull request, please check off relevant items below in the description of your pull request.

---

### Brief description of changes applied

---

### Reference to an Issue, Feature, Task, User Story or another PR

Closes https://github.com/avenirs-esr/AVENIRS-Project/issues/1001

---

### Documentation

---

### Target Branch

---

### Additional Notes

---

### Known Limitations or Side Effects

---

## ✅ Checklist

Please make sure you have addressed the following before submitting:

- [ ] a11y tested (if the PR includes frontend changes)
- [ ] Tests provided (including unit and integration tests for both frontend and backend)
- [ ] i18n handled (texts are translated)
- [ ] Performance tests
- [ ] No unnecessary code (e.g., debug logs, commented code)
- [ ] Code style and formatting rules respected (linting, conventions, etc.)
- [ ] Semantic Versioning respected
- [ ] Add to `CHANGELOG.md` file all properties and database change and detaiils for the update process

---

# Remember

**DO NOT** keep this template as is when you submit. Please remove or adjust the description when you submit your pull request.

Please do not submit a pull request to ask questions.

Do not submit pull requests without tests that verify or reproduce your intended use case. The pull request will
most likely be automatically closed immediately, unless the change is extremely trivial.

### CODE REVIEW

File: src/components/navigation/AvSideMenu/AvSideMenu.vue [hunk 1]
```diff
@@ -151,7 +151,7 @@ function toggleCollapse () {
 }
 
 .av-side-menu__collapse-button {
-  padding: var(--spacing-xs);
+  margin: var(--spacing-xs);
```
Comment (BanelhaqB) [inline src/components/navigation/AvSideMenu/AvSideMenu.vue:155]: j'ai pas testé le rendu mais un padding au contenant serai peut etre plus juste, il n'y a pas que le bouton de fermeture qui est collé tout le contenu, si tu fermes le menu, tu vas voir que toute les icons à l'intérieur  colle la barre latérale.

et puis ce padding semble correcte, il permet au bouton de ressemblé au bouton retour

**Review by BanelhaqB — CHANGES_REQUESTED** [review]
Petite remarque

File: src/components/navigation/AvSideMenu/AvSideMenu.vue (hunk 1 above)
Comment (Nathan-Pignon) [reply src/components/navigation/AvSideMenu/AvSideMenu.vue:155]: Ah je pensais que c'était seulement sur le bouton, mais si c'est tout le conteneur oui le padding serait mieux. Mais si c'était juste sur le bouton le padding ne fonctionne pas car au hover il serait toujours collé au bord ducoup, juste la zone du hover serait plus grosse

Comment (Nathan-Pignon) [reply src/components/navigation/AvSideMenu/AvSideMenu.vue:155]: Après quelques tests je serais resté sur le margin seulement pour le bouton, car si on le fait sur le container, ça ajoute du padding à l'ascenseur ce qui est bizarre je trouve

**Review by BanelhaqB — APPROVED** [review]
C'est good pour moi, merci Nathan
