### PR TITLE
fix(1299): AvMultiselect - prevent jumps in collapse with scroll and add scroll following focus

### LINKED ISSUE #1299: [Bug]: [FE] Le filtre sur le type des documents ne prend pas tout en compte
### Bug Summary

Le filtre sur le type des documents ne prend pas tous les types de document en compte en compte

### Steps to Reproduce

/cofolio/student/tools/traces

### Expected Behavior

Image

### Actual Behavior

Image

### Stacktrace

_No response_

### Related Epic

Epic : #5

### Environment

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by p-beger**
### Brief description of changes applied
This PR fixes visual jump issues in the `MultiselectCollapse` component when opening/closing the multiselect dropdown, and adds scroll-following-focus behavior so that focused options remain visible within a constrained-height list.

**Main changes:**
- 🐛 Refactors `MultiselectCollapse` to prevent layout jumps during collapse animation
- ♿️ Adds `scrollIntoView` on focus in `AvCheckboxListItem` so keyboard navigation keeps focused option visible in a max-height list
- ✨ Adds `collapseMaxHeight` prop to `AvMultiselect` to allow constraining the dropdown list height
- ♻️ Migrates `AvMultiselect` model binding from `modelValue` prop + event to `defineModel`
- 🔥 Removes unused `legend` prop and `useCollapsable` import from `AvMultiselect`
- ✅ Updates unit and a11y tests to reflect new structure
- 📝 Updates `AvMultiselect.md` documentation (new prop, model events section)
- 🍱 Adds `AvMultiselectStub` and exports it in the test barrel
- 📖 Adds `CollapseMaxHeight` Storybook story

---

### Reference to an Issue, Feature, Task, User Story or another PR
Closes https://github.com/avenirs-esr/AVENIRS-Project/issues/1299

---

### Documentation
- `AvMultiselect.md` updated: added `collapseMaxHeight` prop, replaced `update:modelValue` event table with `defineModel` section, removed `modelValue` row
- `AvMultiselect.stories.ts`: new `CollapseMaxHeight` story demonstrating the max-height constraint and keyboard scrolling

**Modified files:**
- `a11y/tests/interaction/selects/AvMultiselect.a11y.test.ts` — add `CollapseMaxHeight` story to a11y suite
- `src/components/interaction/lists/AvCheckboxListItem/AvCheckboxListItem.vue` — add `scrollIntoView` on focus
- `src/components/interaction/selects/AvMultiselect/AvMultiselect.md` — doc update
- `src/components/interaction/selects/AvMultiselect/AvMultiselect.stories.ts` — add `CollapseMaxHeight` story
- `src/components/interaction/selects/AvMultiselect/AvMultiselect.stub.ts` — new stub
- `src/components/interaction/selects/AvMultiselect/AvMultiselect.test.ts` — remove `useCollapsable` mock, adapt assertions
- `src/components/interaction/selects/AvMultiselect/AvMultiselect.vue` — `defineModel` migration, remove `legend`, `collapseMaxHeight` prop
- `src/components/interaction/selects/AvMultiselect/components/MultiselectCollapse.test.ts` — updated tests
- `src/components/interaction/selects/AvMultiselect/components/MultiselectCollapse.vue` — prevent jumps, height management
- `src/tests/index.ts` — export `AvMultiselectStub`

---

### Target Branch
`develop`

---

### Additional Notes
The jump issue was caused by the collapse animation conflicting with the dynamic height of the list. The fix makes the height management explicit via `collapseMaxHeight` and ensures the animation does not cause layout recalculations.

The `defineModel` migration aligns `AvMultiselect` with the rest of the component library and removes the need for the explicit `modelValue` prop.

---

### Known Limitations or Side Effects
Consumers that used the `legend` prop or bound `modelValue` explicitly must migrate to `defineModel` (`v-model`). The `selectedText` prop is now required.

---

## ✅ Checklist

- [ ] a11y tested (`CollapseMaxHeight` story added to a11y suite)
- [ ] Tests provided (unit tests updated for `AvMultiselect` and `MultiselectCollapse`)
- [ ] i18n handled (no new text literals added)
- [ ] Performance tests (no significant performance changes)
- [ ] No unnecessary code (removed unused `legend` prop and `useCollapsable` mock)
- [ ] Code style and formatting rules respected (linting conventions followed)
- [ ] Semantic Versioning respected (conventional commits used)
- [ ] Add to `CHANGELOG.md` file all properties and database change and details for the update process (no database changes; component API change documented above)

### CODE REVIEW

File: src/components/interaction/lists/AvCheckboxListItem/AvCheckboxListItem.vue [hunk 1]
```diff
@@ -70,10 +71,22 @@ function handleFocusPreviousCheckbox (event: KeyboardEvent) {
...
+const listItemRef = ref<InstanceType<typeof AvListItem> | null>(null)
+
+function handleCheckboxFocus () {
+  const el = listItemRef.value
+  if (!el) {
+    return
+  }
+  const domEl = (el instanceof HTMLElement) ? el : (el as { $el: HTMLElement }).$el
+  domEl?.scrollIntoView?.({ block: 'nearest' })
+}
```
Comment (Nathan-Pignon) [inline src/components/interaction/lists/AvCheckboxListItem/AvCheckboxListItem.vue:83]:
```suggestion
function handleCheckboxFocus () {
  const el = listItemRef.value
  if (el) {
  const domEl = (el instanceof HTMLElement) ? el : (el as { $el: HTMLElement }).$el
  domEl?.scrollIntoView?.({ block: 'nearest' })
  }
}
```

**Review by Nathan-Pignon — DISMISSED** [review]
Une petite suggestion mais sinon ok de mon côté, merci Pascal !

File: src/components/interaction/lists/AvCheckboxListItem/AvCheckboxListItem.vue (hunk 1 above)
Comment (p-beger) [reply src/components/interaction/lists/AvCheckboxListItem/AvCheckboxListItem.vue:83]: Bien vu !

**Review by Nathan-Pignon — APPROVED** [review]
